### ISSUE TITLE
init : 패키지 추가

### ISSUE THREAD

**Issue by DoReMinWoo** [Debate-Season/DebateSeason_Frontend_V1#21]
## Description
기본적으로 사용해야 할 패키지 세팅

## ToDo
- API
  - [x] dio
  - [x] retrofit
- 빌드러너
  - [x] build_runner
  - [x] freezed
  - [x] retrofit_generator
  - [x] json_annotation
  - [x] freezed_annotation
- 상태관리
  - [x] getx
- 나머지
  - [x] package_info_plus
  - [x] shared_preferences
  - [x] flutter_native_splash
  - [x] logger
  - [x] flutter_dotenv
  - [x] fluttertoast
  - [x] flutter_svg
  - [x] intl
  - [x] flutter_local_notifications
  - [x] connectivity_plus
- [x] git ignore 추가
- [x] logger 파일 추가
- [x] .env 파일 추가

## ETC
기타 참고사항 작성
