### ISSUE TITLE
init : 프로젝트 구조 정리

### ISSUE THREAD

**Issue by Anzinius** [Debate-Season/DebateSeason_Frontend_V1#23]
## Description
클린 아키텍처와 MVVM 패턴 적용

## ToDo
- [x] 패키지명 변경 `com.rosyocean.debateseason`
- [x] 프로젝트 구조 변경
  ```
  lib/
  ├── core/                     # 공통 모듈 (전역적으로 사용되는 유틸리티, 에러 처리 등)
  │   ├── error/
  │   ├── constants/
  │   ├── interceptor
  │   └── web_socket
  ├── features/
  │   └── chat/                 # 채팅 기능 관련 코드
  │       ├── data/             # 데이터 계층
  │       │   ├── mapper/
  │       │   ├── models/       # API 또는 데이터베이스 모델 정의
  │       │   │   ├── request
  │       │   │   └── response
  │       │   ├── datasources/  # 데이터 소스 정의 (API 호출, 로컬 DB 등)
  │       │   └── repositories_impl/ # Repository 구현체
  │       ├── domain/           # 도메인 계층
  │       │   ├── entities/     # 핵심 엔티티 정의
  │       │   └── repositories/ # Repository 인터페이스
  │       └── presentation/     # 프레젠테이션 계층
  │           ├── types/        # 
  │           ├── views/        # UI 화면 (Flutter 위젯)
  │           └── viewmodels/   # ViewModel (State 관리, MVVM 패턴)
  ├── utils/
  ├── widgets/      # 재사용 가능한 위젯
  └── main.dart      # 앱 진입점
  ```
- [ ] 디자인 시스템 적용
  - [ ] Color
  - [ ] TextStyle

## ETC
- Features/ 단위로 모듈화 된 기능 중심 구조로 갈지 논의 필요

**Comment by Anzinius** [comment]
디자인시스템 관련 폴더링
/constants : 상수
/utils : 함수
/widgets : 위젯
맞나요? @DoReMinWoo
