### ISSUE TITLE
feat : 채팅서버 연결

### ISSUE THREAD

**Issue by Anzinius** [Debate-Season/DebateSeason_Frontend_V1#28]
## Description
채팅서버 연결을 위한 코드 수정

## ToDo
- [x] 채팅서버 연결 확인
- [ ] 채팅 메시지 전송 확인
- [ ] 현 프로젝트 구조에 맞게 파일 리팩토링

## ETC
기타 참고사항 작성

**Comment by Anzinius** [comment]
ToDo1 [채팅서버 연결 확인]은 코드 상 문제가 없는 걸로 확인되어 코드변경없이 completed

**Comment by Anzinius** [comment]
ToDo2, ToDo3 도 생각해보니 필요 없음. 이슈 클로즈하겠습니다.
후에 백엔드랑 aws 관련해서 테스트할 수도 있어 init-structure 는 잠시 놔둘게요. @Doreminwoo
