### ISSUE TITLE
feat : 프로필 입력하기 UI 구현

### ISSUE THREAD

**Issue by Doreminwoo** [Debate-Season/DebateSeason_Frontend_V1#31]
## Description
프로필 입력하기 화면 UI 구현

## ToDo
- [x] 색상확인
- [x] 재사용 텍스트 필드 위젯 구현
- [x] 성별/커뮤니티용 재사용 카드 위젯 구현
- [x] 재사용 바텀 시트 구현
- [x] 유효성 검사 -> 닉네임 정책 필요.

## ETC
기타 참고사항 작성

**Comment by Anzinius** [comment]
오 근데 민우님 프로필 입력하기 제 파트일걸요~?!
